# Generated by Django 5.0.6 on 2026-05-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('pedido_estado', 'Estado de pedido'), ('pago_exito', 'Pago confirmado'), ('recordatorio', 'Recordatorio'), ('cierre_proximo', 'Cierre proximo'), ('general', 'General')], default='general', max_length=30)),
                ('leida', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificacion',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado'],
            },
        ),
    ]
