# Generated by Django 5.0.6 on 2026-05-06 11:12

import django.core.validators
import django.db.models.deletion
import orders.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timeslots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Linea de pedido',
                'verbose_name_plural': 'Lineas de pedido',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente_pago', 'Pendiente de pago'), ('pagado', 'Pagado (en cola)'), ('preparando', 'Preparando'), ('listo', 'Listo para recoger'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente_pago', max_length=20)),
                ('codigo_recogida', models.CharField(default=orders.models.generar_codigo_recogida, editable=False, max_length=10, unique=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notas', models.CharField(blank=True, max_length=300)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('entregado_en', models.DateTimeField(blank=True, null=True)),
                ('franja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='timeslots.timeslot')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado'],
            },
        ),
    ]
