# Generated by Django 5.0.6 on 2026-05-06 11:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono lucide-react (ej: coffee, sandwich)', max_length=40)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Orden de aparicion en el menu')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('imagen_url', models.URLField(blank=True, help_text='URL de la imagen del producto (Unsplash u otra)', max_length=500)),
                ('disponible', models.BooleanField(default=True)),
                ('es_saludable', models.BooleanField(default=False, help_text='Marcar como opcion saludable')),
                ('stock', models.PositiveIntegerField(default=999, help_text='Stock diario. 999 = ilimitado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='products.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria__orden', 'nombre'],
            },
        ),
    ]
