# Generated by Django 5.0.6 on 2026-05-06 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(db_index=True, max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('iniciado', 'Iniciado'), ('exito', 'Exito'), ('fallido', 'Fallido'), ('cancelado', 'Cancelado')], default='iniciado', max_length=20)),
                ('error_mensaje', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='orders.order')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-creado'],
            },
        ),
    ]
